version: '3.12.7'

services:
  web:
    build: .
    container_name: expo
    command: gunicorn --bind 0.0.0.0:8000 expense_tracker.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expo
    ports:
      - "5432:5432"
