# Generated by Django 5.1.4 on 2025-01-03 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_settlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='expenses.session'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='settlement',
            unique_together={('session', 'from_user', 'to_user')},
        ),
    ]
