# Generated by Django 5.0.1 on 2024-12-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
